spring:
  application:
    name: consume-service

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  amqp:
    deserialization:
      trust:
        all: true
server:
  port: 8081

